FROM python:slim
LABEL maintainer="DigiLocker"
LABEL version="1.0"
ENV TZ="Asia/Kolkata"

RUN apt-get update && apt-get install -y libssl-dev libcurl4-openssl-dev python3-dev supervisor net-tools procps
RUN python -m pip install --upgrade pip

RUN pip install -U boto3 flask flask-cors pyjwt pycryptodome python-dotenv redis-py-cluster pika requests bcrypt uuid thefuzz php xmltodict pillow elasticsearch pypdf2 cryptography nltk textblob pdf2image pytesseract pymongo
RUN python -m textblob.download_corpora nltk.downloader stopwords pymongo Pillow python-json-logger captcha gTTS

RUN mkdir -p /etc/supervisord.d
RUN mkdir -p /opt/enc_temp/


RUN apt-get update && \
    apt-get install -y wget && \
    wget https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.5.3-amd64.deb && \
    dpkg -i filebeat-8.5.3-amd64.deb
RUN mkdir -p /opt/entity_auth-py && \
    touch /opt/entity_auth-py/app.log && \
    chmod -R 777 /opt/entity_auth-py

EXPOSE 5000
CMD ["/usr/bin/supervisord", "-n"]