FROM 816586121361.dkr.ecr.ap-south-1.amazonaws.com/entity-auth:base_v1.0
LABEL maintainer="DigiLocker"
LABEL version="1.0"
ENV TZ="Asia/Kolkata"

RUN apt-get update && apt-get install -y libssl-dev libcurl4-openssl-dev python3-dev
RUN pip install -U pymongo
RUN pip install -U captcha gTTS
RUN pip install --upgrade Pillow

COPY config_share/dockerconfig/supervisord.conf /etc/supervisord.conf
COPY config_share/dockerconfig/services.conf /etc/supervisord.d/services.conf

WORKDIR /opt/entity_auth-py
COPY src_code/ /opt/entity_auth-py
COPY config_beta/appconfig/.env /opt/entity_auth-py/
COPY config_beta/ /opt/entity_auth-py/config
COPY config_beta/appconfig/server.py /usr/local/lib/python3.11/http/

EXPOSE 5000
CMD ["/usr/bin/supervisord", "-n"]
