FROM 816586121361.dkr.ecr.ap-south-1.amazonaws.com/entity-auth:base-1.7
MAINTAINER DigiLocker
LABEL version="1.0"
ENV TZ="Asia/Kolkata"

RUN apt-get update && apt-get install -y libssl-dev libcurl4-openssl-dev python3-dev
RUN pip install -U pymongo

WORKDIR /opt/entity_auth-py
COPY src_code/ /opt/entity_auth-py
COPY config_prod/appconfig/.env /opt/entity_auth-py/
COPY config_prod/ /opt/entity_auth-py/config
COPY config_prod/appconfig/server.py /usr/local/lib/python3.11/http/
COPY config_prod/rconfig/consent_key_private.pem /opt/entity_auth-py/rconfig/consent_key_private.pem
CMD [ "python", "app.py" ]
EXPOSE 5000


