FROM 816586121361.dkr.ecr.ap-south-1.amazonaws.com/entity_auth:base-v2.0
LABEL maintainer="DigiLocker"
LABEL version="1.0"
ENV TZ="Asia/Kolkata"

COPY config_share/dockerconfig/supervisord.conf /etc/supervisord.conf
COPY config_share/dockerconfig/services.conf /etc/supervisord.d/services.conf
COPY config_share/dockerconfig/http_ca.crt /etc/filebeat/http_ca.crt

WORKDIR /opt/entity_auth-py
COPY src_code/ /opt/entity_auth-py
COPY config_prod/appconfig/.env /opt/entity_auth-py/
COPY config_prod/ /opt/entity_auth-py/config
COPY config_prod/appconfig/server.py /usr/local/lib/python3.11/http/

EXPOSE 5000
CMD ["/usr/bin/supervisord", "-n"]